spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual.creation: true
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false

server:
  port: 9090

logging:
  level:
    org.springframework.security: TRACE
